---
sidebar: sidebar 
permalink: concept_api_before_workflows.html 
keywords: rest api, deploy rest api, rest, workflows, before you begin 
summary: ワークフロープロセスを確認して使用するための準備をしておく必要があります。 
---
= API ワークフローを使用する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ワークフロープロセスを確認して使用するための準備をしておく必要があります。



== ワークフローで使用されるAPI呼び出しについて理解する

ONTAP Select のオンラインドキュメントページに、すべての REST API 呼び出しの詳細が記載されています。ここでは、それらの詳細を繰り返すのではなく、ワークフローのサンプルで使用している各 API 呼び出しについて、その呼び出しをドキュメントページで見つけるために必要な情報だけを示しています。特定のAPI呼び出しを検索したら、入力パラメータ、出力形式、HTTPステータスコード、要求処理タイプなど、呼び出しのすべての詳細を確認できます。

ワークフロー内の各API呼び出しについて、ドキュメントページで呼び出しを見つけるのに役立つ次の情報が含まれています。

* カテゴリ：ドキュメントページでは、機能的な関連領域またはカテゴリ別に API 呼び出しが分類されています。特定のAPI呼び出しを検索するには、ページの一番下までスクロールし、該当するAPIカテゴリをクリックします。
* HTTP 動詞 HTTP 動詞は、リソースに対して実行する操作を示します。各API呼び出しは、単一のHTTP動詞を使用して実行されます。
* パス：このパスは、呼び出しの実行中に環境 が処理する特定のリソースを指定します。パス文字列がコアURLに追加され、リソースを識別する完全なURLが形成されます。




== REST APIに直接アクセスするためのURLを作成する

ONTAP Select のドキュメントページに加え、 Python などのプログラミング言語を使用して、 Deploy REST API に直接アクセスすることもできます。この場合のコア URL は、オンラインドキュメントページにアクセスするときに使用する URL とは少し異なります。API に直接アクセスする場合は、ドメインとポートの文字列に /api を追加する必要があります。例：
`\http://deploy.mycompany.com/api`
