---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: Representational State Transfer（REST）は、分散Webアプリケーションを作成するための形式です。WebサービスAPIの設計に適用すると、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、 ONTAP Select クラスタの導入と管理のための柔軟な基盤が提供されます。 
---
= 基盤となるREST Webサービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Representational State Transfer（REST）は、分散Webアプリケーションを作成するための形式です。WebサービスAPIの設計に適用すると、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、 ONTAP Select クラスタの導入と管理のための柔軟な基盤が提供されます。



== アーキテクチャと従来の制約

レストは2000年にカリフォルニア大学アーバイン校で博士号を取得したロイ・フィールディングによって正式に明言された https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["失策"]。アーキテクチャスタイルは、一連の制約によって定義されます。これらの制約は、全体的に Web ベースのアプリケーションと基盤となるプロトコルを改善します。制約は、ステートレス通信プロトコルを使用するクライアント / サーバアーキテクチャに基づいて、 RESTful Web サービスアプリケーションを確立するものです。



== リソースと状態の表示

リソースは、Webベースシステムの基本コンポーネントです。REST Webサービスアプリケーションを作成する際の初期設計タスクには、次のものがあります。

* すべてのシステムが使用するシステムまたはサーバベースのリソースを識別し、リソースを維持します。リソースには、ファイル、ビジネストランザクション、プロセス、または管理エンティティがあります。REST Webサービスに基づいてアプリケーションを設計する際の最初のタスクの1つは、リソースを特定することです。
* リソースの状態の定義と関連する状態処理リソースは、常に有限数の状態のいずれかになります。状態、および状態の変化に影響を与えるために使用される関連操作は、明確に定義する必要があります。


クライアントとサーバの間でメッセージを交換しながら、一般的な CRUD （ Create 、 Read 、 Update 、 Delete ）モデルに従ってリソースにアクセスしてその状態を変更します。



== URIエンドポイント

すべてのRESTリソースは、明確に定義されたアドレス指定方式を使用して定義および利用可能にする必要があります。リソースが配置され、識別されるエンドポイントでは、Uniform Resource Identifier（URI）が使用されます。URIは、ネットワーク内の各リソースに一意の名前を作成するための一般的なフレームワークを提供します。Uniform Resource Locator（URL）は、リソースを識別してアクセスするためにWebサービスで使用されるURIの一種です。リソースは通常、ファイルディレクトリに似た階層構造で公開されます。



== HTTP メッセージ

Hypertext Transfer Protocol（HTTP）は、Webサービスのクライアントとサーバがリソースに関する要求と応答のメッセージを交換するために使用するプロトコルです。Web サービスアプリケーションの設計の一環として、 HTTP 動詞（ GET や POST など）はリソースおよび対応する状態管理アクションにマッピングされます。

HTTPはステートレスです。したがって、関連する一連の要求と応答を 1 つのトランザクションで関連付けるには、要求 / 応答のデータフローで伝送される HTTP ヘッダーに追加情報 を含める必要があります。



== JSONの形式

クライアントとサーバの間で情報を構造化して転送する方法は複数ありますが、最も広く使用されている方法（ Deploy REST API で使用）は JavaScript Object Notation （ JSON ）です。JSONは、単純なデータ構造をプレーンテキストで表現するための業界標準であり、リソースを記述する状態情報の転送に使用されます。
