---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。 
---
= Deploy インスタンスをアップグレードする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。



== 開始する前に

アップグレード中に、Deploy を使用して他のタスクを実行しないようにしてください。Deploy ユーティリティのアップグレードに関する情報と制限については、最新のリリースノートを参照してください。


NOTE: ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、現在のリリースにアップグレードする必要があります。ONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます。詳細については、を参照してください link:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^] 。



== アップグレードパッケージをダウンロードする

アップグレード プロセスを開始するには、NetAppサポート サイトから適切なDeploy仮想マシン アップグレード ファイルをダウンロードする必要があります。アップグレードパッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. Web ブラウザを使用してlink:https://mysupport.netapp.com/site/["NetAppサポート サイト"^]にアクセスし、Downloads メニューから *Downloads* を選択します。
. 下にスクロールして*ONTAP Select Deploy Upgrade*を選択してください。
. アップグレード パッケージの目的のリリースを選択します。
. エンドユーザライセンス契約（EULA）を確認し、*同意して続行*を選択します。
. 適切なパッケージを選択してダウンロードし、環境に応じて必要なすべてのプロンプトに応答します。




== パッケージを Deploy 仮想マシンにアップロードします

アップグレードパッケージを取得したら、そのファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
ローカル ワークステーションにアップグレード ファイルを用意しておく必要があります。管理者ユーザー アカウントのパスワードも必要です。

.このタスクについて
このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.手順
. ローカル ワークステーションのコマンド シェルで、scp ユーティリティを使用して、イメージ ファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレードファイルは、 admin ユーザのホームディレクトリに格納されます。



== アップグレードパッケージを適用する

アップグレードファイルが Deploy 仮想マシンにアップロードされたら、アップグレードを適用できます。

.開始する前に
Deploy ユーティリティ仮想マシンのどのディレクトリにアップグレード ファイルが配置されているかを知っておく必要があります。また、アップグレードの実行中は、Deploy を使用して他のタスクを実行しないようにしてください。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. 適切なディレクトリパスとファイル名を使用してアップグレードを実行します。
+
`deploy upgrade -package-path FILEPATH`

+
例

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後
アップグレード手順が完了する前に、Deploy仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたDeployページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
