---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタの導入時に使用できます。 
---
= 導入するONTAP Selectイメージの追加
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタの導入時に使用できます。



== 開始する前に

大まかに言うと、ONTAP Select イメージを Deploy のインスタンスに追加するプロセスは、次の 4 つのステップで構成されます：

. インストールイメージのダウンロード
. インストールイメージを Deploy 仮想マシンにアップロードする
. インストールイメージの追加
. 利用可能なインストールイメージを表示する


新しい ONTAP Select イメージを Deploy に追加する前に、不要なイメージを削除する必要があります。


NOTE: ONTAP Select イメージは、 Deploy ユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンでのみ追加してください。ネットアップから提供される新しいバージョンの ONTAP Select は、サポートされていない構成では追加できません。



== インストールイメージをダウンロードする

ONTAP Select イメージを Deploy ユーティリティのインスタンスに追加するプロセスを開始するには、NetApp Support Siteからインストールイメージをダウンロードする必要があります。ONTAP Select インストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. Web ブラウザーを使用してNetApp Support Siteにアクセスし、*Support Quick Links*をクリックします。
. * トップタスク * の下にある * ソフトウェアのダウンロード * をクリックし、サイトにサインインします。
. *製品を探す* をクリックします。
. 下にスクロールして*ONTAP Select*をクリックします。
. *Other Available Select Software* で、 *Deploy Upgrade, Node Upgrade, Image Install* をクリックします。
. アップグレード パッケージの目的のリリースを選択します。
. エンドユーザーライセンス契約（EULA）を確認し、*Accept & Continue*をクリックします。
. 適切なパッケージを選択してダウンロードし、環境に応じて必要なすべてのプロンプトに応答します。




== インストールイメージをDeployにアップロードする

ONTAP Select インストールイメージを取得したら、ファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
ローカル ワークステーションにインストール イメージ ファイルを用意しておく必要があります。Deploy 管理者ユーザー アカウントのパスワードも必要です。

.タスクの内容
このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.ステップ
. ローカル ワークステーションのコマンド シェルで、イメージ ファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
ノードインストールファイルは、管理者ユーザのホームディレクトリに格納されます。



== インストールイメージを追加する

新しいクラスタの導入時に使用できるように、ONTAP Select インストールイメージを Deploy images ディレクトリに追加できます。

.開始する前に
Deploy ユーティリティの仮想マシンでインストールイメージファイルを配置したディレクトリを確認しておく必要があります。このファイルは、管理者のホームディレクトリにあると想定されます。

.手順
. 管理者（ admin ）アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. Bash シェルを起動します。
+
`shell bash`

. インストール イメージ ファイルを images ディレクトリに配置します。
+
例
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 利用可能なインストールイメージを表示する

新しいクラスターをデプロイするときに使用できる ONTAP Select イメージを表示できます。

.手順
. Deploy ユーティリティの仮想マシンのオンラインドキュメントの Web ページにアクセスし、管理者（ admin ）アカウントを使用してサインインします。
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Deploy 仮想マシンのドメイン名または IP アドレスを使用してください。

. ページの下部に移動して*Deploy*をクリックし、*GET /images*をクリックします。
. *試してみる！*をクリックすると、利用可能なONTAP Selectイメージが表示されます。
. 目的のイメージが使用可能であることを確認します。

