---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加します。インストール後、ONTAP Selectクラスタの導入時に使用できます。 
---
= 導入するONTAP Selectイメージの追加
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加します。イメージをインストールしたら、ONTAP Select クラスタの導入時に使用できます。

.開始する前に
新しい ONTAP Select イメージを Deploy に追加する前に、不要なイメージを削除する必要があります。


NOTE: ONTAP Select イメージは、 Deploy ユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンでのみ追加してください。ネットアップから提供される新しいバージョンの ONTAP Select は、サポートされていない構成では追加できません。



== ステップ1：インストールイメージをダウンロードする

ONTAP Select イメージを Deploy ユーティリティのインスタンスに追加するプロセスを開始するには、NetApp Support Siteからインストールイメージをダウンロードする必要があります。ONTAP Select インストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site ダウンロード"^]ページにアクセスします。
. 下にスクロールして、* ONTAP Select Image *を選択します。
. インストールイメージの目的のリリースを選択します。
. エンドユーザライセンス契約（EULA）を確認し、*同意して続行*を選択します。
. 適切な*ONTAP Select Image Install*パッケージを選択してダウンロードしてください。必要に応じてすべてのプロンプトに応答します。




== ステップ2：インストールイメージをDeployにアップロードする

ONTAP Select インストールイメージを取得したら、ファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
ローカルワークステーションにインストールイメージファイルがあることを確認します。Deploy管理者ユーザーアカウントのパスワードも必要です。

.タスクの内容
このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.ステップ
. ローカル ワークステーションのコマンド シェルで、次の例に示すように、イメージ ファイルを Deploy 仮想マシンにアップロードします：
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
ノードインストールファイルは、管理者ユーザのホームディレクトリに格納されます。



== ステップ3：インストールイメージを追加する

新しいクラスタを導入する際に使用できるように、ONTAP Select インストールイメージを Deploy images ディレクトリに追加します。

.開始する前に
Deploy ユーティリティの仮想マシンでインストールイメージファイルを配置したディレクトリを確認しておく必要があります。このファイルは、管理者のホームディレクトリにあると想定されます。

.手順
. 管理者（ admin ）アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. Bash シェルを起動します。
+
[source, cli]
----
shell bash
----
. 次の例に示すように、インストールイメージファイルを images ディレクトリに配置します：
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== ステップ4：利用可能なインストールイメージを表示する

新しいクラスタを導入する際に使用可能な ONTAP Select イメージを表示します。

.手順
. Deploy ユーティリティの仮想マシンのオンラインドキュメントの Web ページにアクセスし、管理者（ admin ）アカウントを使用してサインインします。
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Deploy 仮想マシンのドメイン名または IP アドレスを使用してください。

. ページの下部に移動して *Deploy* を選択し、次に *GET /images* を選択します。
. *試してみる！*を選択すると、利用可能なONTAP Selectイメージが表示されます。
. 目的のイメージが使用可能であることを確認します。

